"""python-craft templates for first-class LSP activation."""

from .atlas_polar_field import (
    MOOD_PALETTES,
    SEEDS,
    EntityPoint,
    Trail,
)
from .atlas_polar_field import (
    render as polar_field_render,
)
from .caraxes_fireworks import (
    DragonSpec,
    FireworksSpec,
    GlassSpec,
    MoonblastSpec,
    RidgeSpec,
    SkyGradientSpec,
    VolcanoSpec,
    demo_fireworks,
    fireworks_render,
)
from .context_weave import (
    COMMUNITY_REFS,
    ELIGIBILITY_DIMS,
    FLUORESCENCE,
    GEOANCHORS,
    RESEARCH_WAVES,
    WARM_SPECTRUM,
    CommunityRef,
    EligibilityDimension,
    GeoAnchor,
    PersonaBlock,
    ResearchWave,
    ShiftCycle,
    TemporalFilter,
    compute_fold_contrast,
)
from .context_weave import (
    demo as demo_context_weave,
)
from .context_weave import (
    render as context_weave_render,
)
from .gruff_geometric_sketch import (
    CompassSpec,
    CompassXSpec,
    PaperSpec,
    Render360Spec,
    ShiftCycleSpec,
    demo,
    demo_360,
    demo_compass_x,
    demo_shift_cycles,
    gruff_compass_x_contrast_render,
    gruff_shift_cycles_render,
    gruff_sketch,
    gruff_wide_360_render,
)
from .gridstral_profile import (
    GRIDSTRAL_AGENT_ID,
    GRIDSTRAL_AGENT_VERSION,
    GRIDSTRAL_LABEL,
    short_agent_id,
)
from .routine_field_render import (
    AttentionSpec,
    GateSpec,
    GovernanceSpec,
    demo_routine_field,
    render_attention_field,
    render_gate_contrast,
    render_governance,
    render_phase_cycles,
    render_unified_360,
)
from .sylveon_heatmap import (
    CompassAddonSpec,
    SylveonRun,
    SylveonSpec,
    TodoRecommendation,
    demo_sylveon,
    sylveon_render,
)

__all__ = [
    "PaperSpec",
    "CompassSpec",
    "CompassXSpec",
    "Render360Spec",
    "ShiftCycleSpec",
    "gruff_sketch",
    "gruff_wide_360_render",
    "gruff_compass_x_contrast_render",
    "gruff_shift_cycles_render",
    "GRIDSTRAL_AGENT_ID",
    "GRIDSTRAL_AGENT_VERSION",
    "GRIDSTRAL_LABEL",
    "short_agent_id",
    "demo",
    "demo_360",
    "demo_compass_x",
    "demo_shift_cycles",
    "SylveonSpec",
    "CompassAddonSpec",
    "TodoRecommendation",
    "SylveonRun",
    "sylveon_render",
    "demo_sylveon",
    "FireworksSpec",
    "SkyGradientSpec",
    "MoonblastSpec",
    "VolcanoSpec",
    "DragonSpec",
    "GlassSpec",
    "RidgeSpec",
    "fireworks_render",
    "demo_fireworks",
    # atlas_polar_field
    "EntityPoint",
    "Trail",
    "SEEDS",
    "MOOD_PALETTES",
    "polar_field_render",
    # context_weave
    "GeoAnchor",
    "GEOANCHORS",
    "PersonaBlock",
    "TemporalFilter",
    "ResearchWave",
    "RESEARCH_WAVES",
    "CommunityRef",
    "COMMUNITY_REFS",
    "EligibilityDimension",
    "ELIGIBILITY_DIMS",
    "WARM_SPECTRUM",
    "FLUORESCENCE",
    "ShiftCycle",
    "compute_fold_contrast",
    "context_weave_render",
    "demo_context_weave",
    # routine_field_render
    "GovernanceSpec",
    "AttentionSpec",
    "GateSpec",
    "render_governance",
    "render_attention_field",
    "render_gate_contrast",
    "render_phase_cycles",
    "render_unified_360",
    "demo_routine_field",
]
